package com.johnmartin.pump.controller;

import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.johnmartin.pump.constants.api.ApiConstants;
import com.johnmartin.pump.constants.api.ApiErrorMessages;
import com.johnmartin.pump.constants.entities.CommentEntityConstants;
import com.johnmartin.pump.dto.request.CreateCommentRequest;
import com.johnmartin.pump.dto.response.CommentResponse;
import com.johnmartin.pump.dto.response.Result;
import com.johnmartin.pump.entities.CommentEntity;
import com.johnmartin.pump.entities.UserEntity;
import com.johnmartin.pump.mapper.CommentMapper;
import com.johnmartin.pump.service.CommentService;
import com.johnmartin.pump.service.PostService;
import com.johnmartin.pump.service.UserService;
import com.johnmartin.pump.utilities.LoggerUtility;
import com.johnmartin.pump.utils.ApiErrorUtils;

@RestController
@RequestMapping(ApiConstants.Path.API_COMMENT)
public class CommentController {

    private static final String DEBUG_TAG = CommentController.class.getSimpleName();

    @Autowired
    private CommentService commentService;

    @Autowired
    private UserService userService;

    @Autowired
    private PostService postService;

    @PostMapping
    public ResponseEntity<Result<CommentResponse>> createComment(@PathVariable(ApiConstants.Params.POST_ID) String postId,
                                                                 @RequestBody CreateCommentRequest request) {
        Optional<UserEntity> dbUserEntity = userService.findById(request.getUserId());
        if (dbUserEntity.isEmpty()) {
            return ApiErrorUtils.createUnauthorizedErrorResponse(ApiErrorMessages.User.INVALID_CREDENTIALS);
        }

        try {
            CommentEntity createdComment = new CommentEntity();
            createdComment.setComment(request.getComment());
            createdComment.setUserId(request.getUserId());
            createdComment.setPostId(postId);
            createdComment.setUserName(dbUserEntity.get().getFirstName() + " " + dbUserEntity.get().getLastName());
            createdComment.setUserProfileImageUrl(dbUserEntity.get().getProfileImageUrl());
            createdComment.setLikesCount(0);
            createdComment.setRepliesCount(0);

            // ID and Dates are generated by MongoDB after insertion
            CommentEntity commentToBeReturned = commentService.saveComment(createdComment);

            // // Update Post status
            // postService.incrementCommentsCount(postId);

            return ResponseEntity.status(HttpStatus.CREATED)
                                 .body(Result.success(CommentMapper.toResponse(commentToBeReturned)));
        } catch (Exception e) {
            LoggerUtility.e(DEBUG_TAG, e.getMessage(), e);
            return ApiErrorUtils.createInternalServerErrorResponse(ApiErrorMessages.INTERNAL_SERVER_ERROR);
        }
    }

    @GetMapping
    public ResponseEntity<Result<List<CommentResponse>>> getComments(@PathVariable(CommentEntityConstants.COLUMN_POST_ID) String postId) {
        // try {
        // List<CommentEntity> comments = Optional.ofNullable(commentService.getCommentsFromPost(postId))
        // .orElse(Collections.emptyList());
        //
        // if (CollectionUtils.isEmpty(comments)) {
        // return ApiErrorUtils.createNotFoundErrorResponse(ApiErrorMessages.Post.THERE_ARE_NO_COMMENTS_AVAILABLE);
        // }
        //
        // List<CommentResponse> commentResponseList = new ArrayList<>(comments.stream()
        // .map(CommentMapper::toResponse)
        // .toList());
        //
        // // Sort comments from oldest to newest
        // commentResponseList.sort(Comparator.comparing(CommentResponse::getCreatedAt));
        // LoggerUtility.v(DEBUG_TAG, String.format("Sorted commentResponseList: [%s]", commentResponseList));
        // return ResponseEntity.ok(Result.success(commentResponseList));
        // } catch (Exception e) {
        // LoggerUtility.e(DEBUG_TAG, e.getMessage(), e);
        // return ApiErrorUtils.createInternalServerErrorResponse(ApiErrorMessages.INTERNAL_SERVER_ERROR);
        // }
        return ApiErrorUtils.createInternalServerErrorResponse(ApiErrorMessages.INTERNAL_SERVER_ERROR);

    }
}
