package com.johnmartin.pump.controller;

import java.util.*;

import org.apache.commons.collections4.CollectionUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.johnmartin.pump.constants.ApiConstants;
import com.johnmartin.pump.constants.ApiErrorMessages;
import com.johnmartin.pump.dto.request.CreatePostRequest;
import com.johnmartin.pump.dto.response.CommentResponse;
import com.johnmartin.pump.dto.response.PostResponse;
import com.johnmartin.pump.dto.response.Result;
import com.johnmartin.pump.entities.CommentEntity;
import com.johnmartin.pump.entities.PostEntity;
import com.johnmartin.pump.entities.UserEntity;
import com.johnmartin.pump.mapper.CommentMapper;
import com.johnmartin.pump.mapper.PostMapper;
import com.johnmartin.pump.service.CommentService;
import com.johnmartin.pump.service.PostService;
import com.johnmartin.pump.service.UserService;
import com.johnmartin.pump.utilities.LoggerUtility;
import com.johnmartin.pump.utils.ApiErrorUtils;

@RestController
@RequestMapping(ApiConstants.Path.API_POST)
public class PostController {

    private static final String DEBUG_TAG = PostController.class.getSimpleName();

    @Autowired
    private PostService postService;

    @Autowired
    private UserService userService;

    @Autowired
    private CommentService commentService;

    @GetMapping
    public ResponseEntity<Result<List<PostResponse>>> getPosts() {
        try {
            List<PostEntity> posts = Optional.ofNullable(postService.getPosts()).orElse(Collections.emptyList());

            if (CollectionUtils.isEmpty(posts)) {
                return ApiErrorUtils.createNotFoundErrorResponse(ApiErrorMessages.Post.THERE_ARE_NO_POST_AVAILABLE);
            }

            List<PostResponse> postResponseList = new ArrayList<>();
            for (PostEntity post : posts) {
                // Get comments from post
                List<CommentEntity> commentEntityList = commentService.getCommentsFromPost(post.getId());
                List<CommentResponse> commentResponseList = new ArrayList<>(commentEntityList.stream()
                                                                                             .map(CommentMapper::toResponse)
                                                                                             .toList());

                // Sort comments from oldest to newest
                commentResponseList.sort(Comparator.comparing(CommentResponse::getCreatedAt));
                PostResponse postResponse = PostMapper.toResponse(post, commentResponseList, post.getUserId());
                postResponseList.add(postResponse);
            }

            // Sort posts from newest to oldest
            postResponseList.sort(Comparator.comparing(PostResponse::getCreatedAt).reversed());
            LoggerUtility.v(DEBUG_TAG, String.format("Sorted postResponseList: [%s]", postResponseList));
            return ResponseEntity.ok(Result.success(postResponseList));
        } catch (Exception e) {
            LoggerUtility.e(DEBUG_TAG, e.getMessage(), e);
            return ApiErrorUtils.createInternalServerErrorResponse(ApiErrorMessages.INTERNAL_SERVER_ERROR);
        }
    }

    @PostMapping
    public ResponseEntity<Result<PostResponse>> createPost(@RequestBody CreatePostRequest request) {
        Optional<UserEntity> dbUserEntity = userService.findById(request.getUserId());
        if (dbUserEntity.isEmpty()) {
            return ApiErrorUtils.createUnauthorizedErrorResponse(ApiErrorMessages.User.USER_IS_NOT_AUTHENTICATED);
        }

        try {
            PostEntity createdPost = new PostEntity();
            createdPost.setTitle(request.getTitle());
            createdPost.setDescription(request.getDescription());
            createdPost.setUserId(request.getUserId());
            createdPost.setUserName(dbUserEntity.get().getFirstName() + " " + dbUserEntity.get().getLastName());
            createdPost.setUserProfileImageUrl(dbUserEntity.get().getProfileImageUrl());
            createdPost.setLikesCount(0);
            createdPost.setCommentsCount(0);
            createdPost.setSharesCount(0);

            // ID and Dates are generated by MongoDB after insertion
            PostEntity postToBeReturned = postService.savePost(createdPost);
            LoggerUtility.v(DEBUG_TAG, String.format("postToBeReturned: [%s]", postToBeReturned));
            return ResponseEntity.status(HttpStatus.CREATED)
                                 .body(Result.success(PostMapper.toResponse(postToBeReturned,
                                                                            new ArrayList<>(),
                                                                            request.getUserId())));
        } catch (Exception e) {
            LoggerUtility.e(DEBUG_TAG, e.getMessage(), e);
            return ApiErrorUtils.createInternalServerErrorResponse(ApiErrorMessages.INTERNAL_SERVER_ERROR);
        }
    }

    @PostMapping(ApiConstants.Path.POST_LIKE)
    public ResponseEntity<Result<PostResponse>> likePost(@PathVariable(ApiConstants.Params.POST_ID) String postId) {
        Optional<UserEntity> userOpt = userService.getAuthenticatedUser();
        if (userOpt.isEmpty()) {
            return ApiErrorUtils.createUnauthorizedErrorResponse(ApiErrorMessages.User.USER_IS_NOT_AUTHENTICATED);
        }

        try {
            // Get post info
            PostEntity post = postService.getPostById(postId);
            if (post == null) {
                return ApiErrorUtils.createNotFoundErrorResponse(ApiErrorMessages.Post.POST_NOT_FOUND);
            } else {
                // Prevent double-like
                if (!CollectionUtils.containsAny(post.getLikedUserIds(), userOpt.get().getId())) {
                    postService.likePost(postId, userOpt.get().getId());

                    List<CommentEntity> commentEntityList = commentService.getCommentsFromPost(post.getId());
                    List<CommentResponse> commentResponseList = new ArrayList<>(commentEntityList.stream()
                                                                                                 .map(CommentMapper::toResponse)
                                                                                                 .toList());
                    PostResponse updatedPost = PostMapper.toResponse(postService.getPostById(postId),
                                                                     commentResponseList,
                                                                     userOpt.get().getId());
                    return ResponseEntity.ok(Result.success(updatedPost));
                }
            }
        } catch (Exception e) {
            LoggerUtility.e(DEBUG_TAG, e.getMessage(), e);
            return ApiErrorUtils.createInternalServerErrorResponse(ApiErrorMessages.INTERNAL_SERVER_ERROR);
        }

        return ApiErrorUtils.createInternalServerErrorResponse(ApiErrorMessages.INTERNAL_SERVER_ERROR);
    }
}
