package com.johnmartin.pump.service;

import java.util.List;

import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;

import com.johnmartin.pump.constants.UIConstants;
import com.johnmartin.pump.constants.api.ApiErrorMessages;
import com.johnmartin.pump.dto.request.CreateCommentRequest;
import com.johnmartin.pump.dto.response.CommentResponse;
import com.johnmartin.pump.entities.CommentEntity;
import com.johnmartin.pump.entities.PostEntity;
import com.johnmartin.pump.entities.UserEntity;
import com.johnmartin.pump.exception.BadRequestException;
import com.johnmartin.pump.exception.ResourceNotFoundException;
import com.johnmartin.pump.exception.UnauthorizedException;
import com.johnmartin.pump.mapper.CommentMapper;
import com.johnmartin.pump.repository.CommentRepository;
import com.johnmartin.pump.service.core.BaseService;
import com.johnmartin.pump.utilities.LoggerUtility;

import jakarta.transaction.Transactional;

@Service
public class CommentService extends BaseService {

    private static final String DEBUG_TAG = CommentService.class.getSimpleName();

    @Autowired
    private CommentRepository commentRepository;

    @Autowired
    private PostService postService;

    /**
     * Get comments
     * 
     * @param postId
     *            - Post ID
     * @param page
     *            - page
     * @return List of CommentResponse
     */
    public List<CommentResponse> getComments(String postId, int page) {
        PageRequest pageRequest = PageRequest.of(page, UIConstants.MINIMUM_COMMENTS_PER_POST);
        List<CommentEntity> commentEntityList = commentRepository.findByPostIdOrderByCreatedAtDesc(postId, pageRequest);
        return commentEntityList.stream().map(CommentMapper::toResponse).toList();
    }

    /**
     * Create a comment
     * 
     * @param postId
     *            - Post ID
     * @param request
     *            - CreateCommentRequest
     * @return CommentResponse
     */
    public CommentResponse createComment(String postId, CreateCommentRequest request) {
        LoggerUtility.d(DEBUG_TAG,
                        String.format("Execute method: [createComment] postId: [%s] request: [%s]", postId, request));

        if (StringUtils.isBlank(postId) || request == null) {
            throw new BadRequestException(ApiErrorMessages.Post.POST_ID_IS_REQUIRED);
        }

        PostEntity post = postService.getPostById(postId);
        UserEntity user = getAuthenticatedUser();

        CommentEntity createdComment = new CommentEntity();
        createdComment.setComment(request.getComment());
        createdComment.setUserId(user.getId());
        createdComment.setPostId(post.getId());
        createdComment.setUserName(user.getFirstName() + " " + user.getLastName());
        createdComment.setUserProfileImageUrl(user.getProfileImageUrl());
        createdComment.setLikesCount(0);
        createdComment.setRepliesCount(0);

        // ID and Dates are generated by MongoDB after insertion
        CommentEntity commentToBeReturned = saveComment(createdComment);
        LoggerUtility.v(DEBUG_TAG, String.format("commentToBeReturned: [%s]", commentToBeReturned));
        return CommentMapper.toResponse(commentToBeReturned);
    }

    /**
     * Delete a comment
     * 
     * @param commentId
     *            - Comment ID
     */
    public void deleteComment(String postId, String commentId) {
        LoggerUtility.d(DEBUG_TAG,
                        String.format("Execute method: [deleteComment] postId: [%s] commentId: [%s]",
                                      postId,
                                      commentId));

        if (StringUtils.isBlank(postId)) {
            throw new BadRequestException(ApiErrorMessages.Post.POST_ID_IS_REQUIRED);
        }

        if (StringUtils.isBlank(commentId)) {
            throw new BadRequestException(ApiErrorMessages.Comment.COMMENT_ID_IS_REQUIRED);
        }

        UserEntity user = getAuthenticatedUser();
        CommentEntity comment = getCommentById(commentId);

        // Should i add this?
        PostEntity post = postService.getPostById(postId);

        // Ensure comment belongs to the post
        if (!comment.getPostId().equals(postId)) {
            throw new BadRequestException(ApiErrorMessages.Comment.THE_COMMENT_DOES_NOT_BELONG_TO_THE_SPECIFIED_POST);
        }

        // Only comment owner can delete
        if (!comment.getUserId().equals(user.getId())) {
            throw new UnauthorizedException(ApiErrorMessages.User.YOU_ARE_NOT_AUTHORIZED_TO_PERFORM_THIS_ACTION);
        }

        // Delete comment
        commentRepository.deleteById(commentId);

        // Decrement post comment count
        postService.decrementCommentsCount(postId);
    }

    /**
     * Save a comment then increment post's comments count
     * 
     * @param comment
     *            - Comment
     * @return CommentEntity
     */
    @Transactional
    public CommentEntity saveComment(CommentEntity comment) {
        CommentEntity savedComment = commentRepository.save(comment);
        postService.incrementCommentsCount(comment.getPostId());
        return savedComment;
    }

    /**
     * Delete post
     * 
     * @param postId
     *            - Post ID
     */
    public void deleteByPostId(String postId) {
        PostEntity post = postService.getPostById(postId);
        commentRepository.deleteByPostId(post.getId());
    }

    /**
     * Get comment by ID
     *
     * @param commentId
     *            - Comment ID
     * @return CommentEntity
     */
    private CommentEntity getCommentById(String commentId) {
        return commentRepository.findById(commentId)
                                .orElseThrow(() -> new ResourceNotFoundException(ApiErrorMessages.Comment.COMMENT_NOT_FOUND));
    }
}
