package com.johnmartin.pump.service;

import java.util.ArrayList;

import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.johnmartin.pump.constants.api.ApiErrorMessages;
import com.johnmartin.pump.dto.request.CreatePostRequest;
import com.johnmartin.pump.dto.response.PostResponse;
import com.johnmartin.pump.entities.PostEntity;
import com.johnmartin.pump.entities.UserEntity;
import com.johnmartin.pump.exception.BadRequestException;
import com.johnmartin.pump.exception.ResourceNotFoundException;
import com.johnmartin.pump.mapper.PostMapper;
import com.johnmartin.pump.repository.PostRepository;
import com.johnmartin.pump.service.core.BaseService;
import com.johnmartin.pump.utilities.LoggerUtility;

@Service
public class PostService extends BaseService {

    private static final String DEBUG_TAG = PostService.class.getSimpleName();

    @Autowired
    private PostRepository postRepository;

    /**
     * Create a post
     * 
     * @param request
     *            - CreatePostRequest
     * @return PostResponse
     */
    public PostResponse createPost(CreatePostRequest request) {
        LoggerUtility.d(DEBUG_TAG, String.format("Execute method: [createPost] request: [%s]", request));

        if (request == null) {
            throw new BadRequestException(ApiErrorMessages.INVALID_REQUEST);
        }

        if (StringUtils.isBlank(request.getDescription())) {
            throw new BadRequestException(ApiErrorMessages.Post.POST_DESCRIPTION_IS_REQUIRED);
        }

        UserEntity user = getAuthenticatedUser();

        PostEntity createdPost = new PostEntity();
        createdPost.setTitle(request.getTitle());
        createdPost.setDescription(request.getDescription());
        createdPost.setUserId(user.getId());
        createdPost.setUserName(user.getFirstName() + " " + user.getLastName());
        createdPost.setUserProfileImageUrl(user.getProfileImageUrl());
        createdPost.setLikesCount(0);
        createdPost.setCommentsCount(0);
        createdPost.setSharesCount(0);

        LoggerUtility.v(DEBUG_TAG, String.format("createdPost: [%s]", createdPost));

        // ID and Dates are generated by MongoDB after insertion
        PostEntity postToBeReturned = postRepository.save(createdPost);
        LoggerUtility.v(DEBUG_TAG, String.format("postToBeReturned: [%s]", postToBeReturned));
        return PostMapper.toResponse(postToBeReturned, new ArrayList<>(), user.getId());
    }

    /**
     * Increment comments count
     * 
     * @param postId
     *            - Post ID
     */
    public void incrementCommentsCount(String postId) {
        PostEntity post = getPostById(postId);
        postRepository.incrementCommentsCount(post.getId());
    }

    /**
     * Decrement comments count
     *
     * @param postId
     *            - Post ID
     */
    public void decrementCommentsCount(String postId) {
        PostEntity post = getPostById(postId);
        postRepository.decrementCommentsCount(post.getId());
    }

    /**
     * Get post by post ID
     *
     * @param postId
     *            - Post ID
     * @return PostEntity or null
     */
    public PostEntity getPostById(String postId) {
        return postRepository.findById(postId)
                             .orElseThrow(() -> new ResourceNotFoundException(ApiErrorMessages.Post.POST_NOT_FOUND));
    }
}
